[build-system]
requires = ["setuptools >= 47.1.1", "wheel >= 0.34.2"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
src_paths = ["hmmer_reader"]
known_third_party = ["click", "pandas", "importlib-resources", "pytest"]
